### ISSUE TITLE
Container not available, questions

### ISSUE THREAD

**Issue by bgalvao** [kurowasan/GraN-DAG#1]
Hi, I want to run GraN-DAG with my dataset. However, as soon as I tried to open the link to the container, google drive returned me "Page not found".

I loved reading your paper!

**Comment by kurowasan** [comment]
Hi 0x2A! 

You are right, I will put the container back tomorrow. Sorry for the inconvinience. 

Thank you for your interest :) !

**Comment by kurowasan** [comment]
Ok, the container is back online! 

If there are any other problems, feel free to contact me again!

**Comment by bgalvao** [comment]
Thanks!
