### ISSUE TITLE
How to Run the Code?

### ISSUE THREAD

**Issue by hechuan-wen** [kurowasan/GraN-DAG#2]
Hi there,

I follow the instruction you leave, install Singularity and don't know how to run your "container.simg". I'm sure many people will have the same confusion... I just very new to something called "container" and "Singularity", really have no idea about how to run it. I spend hours and have no way due to my stupid. 

Can you please have some further detailed instruction?

Regard

**Comment by kurowasan** [comment]
Hi there!

Have you installed Singularity and downloaded the container? If not, at what step are you stucked?

If you have Singularity and the container, then to run the container you just need to execute the shell script "start_example.sh" (and make sure to change the name of the directories).

If you can give more details on where you are stucked, I'd be happy to help!

**Comment by hechuan-wen** [comment]
Hi Philippe,

Thanks for reply! I gradually work it out. Since I run it on my Mac, and the Singularity only supports the Linux system. I then use the VirtualBox to create an virtual machine to install Singularity.

The problem is I'm not very familiar with the operation using the shell in the virtual machine operating Singularity... After trying very long time, I literally give it up before I turned to a senior programmer. He solved my problem to run your code (He also spend hours since there are really some problems to link the virtual machine working directory with the host machine (my Mac) local folder).

But very unfortunately, even though I get the program running, because the RAM of my Mac is too small, I allocate 4GB RAM to the virtual machine to run your code but not enough though, then, the program just break and exit. I don't work on it after then cuz my computer limitation).

"In conclusion", I think I need a real Linux system computer (sadly, I just have a Mac) to run your code instead of using MacOS, otherwise there are many potential problems. If possible, I think it's more user-friendly if you can test your program on Mac or Windows system and give some recommendation to the readers. Anyway, it's all good for me atm.

Thanks again

Regard,
Hechuan
________________________________
